### ISSUE TITLE
Investigate REST api

### ISSUE THREAD

**Issue by titaniumbones** [org2blog/org2blog#203]
WP 4.4 seems to be moving to a new API:

https://wordpress.org/plugins/rest-api/

It may have existed before, but I wasn't aware of it.  I wouldn't be surprised if xmlrpc starts to suffer bitrot; it might be worth investigating the new API.  Probably quite a lot of work.  It does open up new possibilities for managing wordpress from within Emacs -- I can imagine it becoming very powerful.

**Comment by grettke** [comment]
Thanks for posting this.

**Comment by raamdev** [comment]
Yes, this would be great! I was just researching org2blog support for Post Formats (which the WordPress XMLRPC [has supported since WP v3.1](https://codex.wordpress.org/XML-RPC_MetaWeblog_API#metaWeblog.newPost), ~6 years ago) and sadly it appears that org2blog does not support that. However, working towards implementing the new REST API (which is intended to eventually replace the XMLRPC altogether) would definitely be a better way to go.

http://v2.wp-api.org/

**Comment by grettke** [comment]
Good to know. Consider it investigated.

When we must switch, we will.
