### ISSUE TITLE
Linking a file without an extension fails

### ISSUE THREAD

**Issue by hexa00** [org2blog/org2blog#211]
[Trying to link [[file:///test]] will fail with the following backtrace:

  mailcap-extension-to-mime(nil)
  get-file-properties("/test")
  org2blog/wp-upload-files-replace-urls....
  org2blog/wp--export-as-html(nil (:section-numbers nil :with-priority nil :with-sub-superscript nil :with-toc nil :with-tags nil :with-todo-keywords nil :wp-keep-new-lines nil :wp-latex t :wp-shortcode nil :tags-as-categories nil :wp-shortcode-langs-map nil))
  org2blog/wp--export-as-post(nil)
  org2blog/wp-post-buffer-as-page(t)
  org2blog/wp-post-buffer-as-page-and-publish()

Could we make it default to text ?

Using version : 20151208.828 from MELPA.

Thanks,
Antoine

**Comment by grettke** [comment]
@hexa00 That makes sense. Details are in the picture at the end.

@punchagan I want to add support for a file without an extension. Instead of using `mailcap-extension-to-mime` in `get-file-properties` I will look it up manually. That helper function requires a file extension, so it can't lookup the "no file name extension" case that _would_ return text/plain. I put in a request to maintain metaweblog so if that sounds good then I will move this issue there.

![screenshot 2017-06-17 21 24 59](https://user-images.githubusercontent.com/2521647/27257810-a7a04c5c-53aa-11e7-9bcb-0ee31ba55a9b.png)

**Comment by grettke** [comment]
Revisiting this, like @hexa00 shared, [text is the default MIME type for text files](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types).

**Comment by grettke** [comment]
[Here](https://github.com/org2blog/metaweblog/commit/59611faeb02de642f75f4bed2aed6b2df97fb1ed) is the fix. 

I incremented this release to pull it in.

**Comment by hexa00** [comment]
@grettke  thanks!

**Comment by grettke** [comment]
@hexa00 You are welcome. Have a great day.
