### ISSUE TITLE
Research multi-byte posting issue

### ISSUE THREAD

**Issue by grettke** [org2blog/org2blog#225]
[Issue 223](https://github.com/punchagan/org2blog/issues/223) described a problem solved [here](http://blog.somof.net/?p=1310) . The code from that post is attached verbatim.
[mb.el.zip](https://github.com/punchagan/org2blog/files/709370/mb.el.zip)

**Comment by taingra** [comment]
Here's the bug in the [Emacs bug tracker](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=23750)

> This particular bug came from this:

> "Content-length: " (number-to-string (length url-http-data))

> Which gives wrong value when url-http-data is multibyte (it should be 
length in bytes). So then, the HTTP server on the other side saw the 
wrong body length and truncated the body when reading the request. Or 
something along these lines.

From the bug tracker it sounded like encode-coding-string could be helpful in doing dealing with multi-byte strings. Basically my guess is the body text of the post is not being properly encoded into UTF-8 and now Emacs checks for it and stops you if it isn't properly encoded when making a http request. Which is why commenting out the check makes it work again.

Disclaimer: I am really inexperienced with this kind of thing, just trying to learn and help solve an issue I ran into.

**Comment by grettke** [comment]
Thank you for the link and explanation? Seems like it is expected that we deal with this on our end. I will keep reading.

**Comment by grettke** [comment]
So, we should only ever use ASCII or UTF-8 characters with that library... and `string-to-unibyte` will generate that but it will break every other encoding... if I am reading that right.

**Comment by grettke** [comment]
@taingra What encoding do you use for Chinese? UTF-8?

**Comment by grettke** [comment]
[This post](http://nullprogram.com/blog/2014/06/13/) seems to explain a lot of what the discussion thread is covering.

**Comment by taingra** [comment]
@grettke For me I actually ran into the issue when trying to post some output from systemctl which uses '●' and was UTF-8 encoded, so I'm not sure about Chinese.

**Comment by grettke** [comment]
@taingra That makes sense because its all Unicode. 

The discussion thread explains how people are using the library wrong. The fix posted in tracker restores and older version of that function which doesn't die on "wrong" usage. 

I just don't know how to use it "right".

**Comment by grettke** [comment]
@taingra It has been a while but if you can please try out his patched xml-rpc.el for your use case.
[fix.zip](https://github.com/org2blog/org2blog/files/1099213/fix.zip)

**Comment by grettke** [comment]
Here is the fix either [as a file](https://github.com/grettke/xml-rpc-el/blob/master/xml-rpc.el) or [make the change](https://github.com/hexmode/xml-rpc-el/pull/6/files) in your copy of of `xml-rpc.el` for example that you pull down using `use-package`.

**Comment by cpbotha** [comment]
I ran into the `url-http-create-request: Multibyte text in HTTP request: POST /xmlrpc.php HTTP/1.1` trying to publish https://vxlabs.com/2017/12/08/variational-autoencoder-in-pytorch-commented-and-annotated/

Your xml-rpc.el patch fixed it at least for my setup. Thanks!

**Comment by grettke** [comment]
@cpbotha Glad to hear and thanks for letting us know. I'm going to update these posts to link to the fix. Thanks and have a great day.

**Comment by grettke** [comment]
This issue is resolved here [here using this patch](https://github.com/org2blog/org2blog#unicode-character-support).
