### ISSUE TITLE
More detailed usage guide: workflow

### ISSUE THREAD

**Issue by grettke** [org2blog/org2blog#233]
Workflow is to write content in o2b and post it to WP. 

Any other workflow will fail in confusing and unexpected ways.

**Comment by aspiers** [comment]
Stupid question, but what other workflows are there? :-)  (Other than import, which is mentioned in #236.)

**Comment by grettke** [comment]
@aspiers Maybe I submitted a dumb issue? :)

When I put myself in the shoes of a first-time poster I want to know as little as possible in order for me to post. I don't want to have to read the entire readme about all of the details and options and commands. I just want to post to my blog.

So maybe under the first heading on the page, just one heading it could the bare minimum:
- Install using use-package except for xml-rpc, use the patched version. Don't even discuss wanting to use Unicode or not.
- Define your blog. maybe you don't have to store your password the first time because you can log in by typing your password.
- Write and publish your post

That was the idea at least today.

However, you are right: I had meant it to add a note that this is a one-way publishing platform from Org2Blog to WordPress... at least until we change that. Thanks for helping me remember two truths.

**Comment by aspiers** [comment]
No, I don't think you submitted a dumb issue :)  Probably I just slightly misunderstood it.  Your reference to "any other workflow" just had me wondering what other workflows there might be, and how they would fail.  But it sounds like you are talking more about improving the structure of the docs so that it is more focused and easier to get quickly started as a beginner, and that sounds like a great idea.

But I just realised there *are* other workflows, e.g. post as a draft first, then later publish...

**Comment by grettke** [comment]
I hear you.

**Comment by grettke** [comment]
Added the workflow [here](https://github.com/org2blog/org2blog/wiki/Workflow%20And%20Data%20Consistency).

**Comment by aspiers** [comment]
Awesome!

**Comment by grettke** [comment]
@aspiers After reading it, I feel like there are some places to expand and refine, so I will do that, and let you know.
