### ISSUE TITLE
How do you allow for "Publish: immediately"?

### ISSUE THREAD

**Issue by neonnoodle** [org2blog/org2blog#250]
Org2Blog works great! I have a question, though. Normally I want to create drafts that don't have a date. They're going to be published at some point in the future, and I don't want them to be backdated when it's time to publish. In the WP Dashboard, new posts default to "Publish: Immediately." Whenever you hit the Publish button, they are published as-of that date/time.

Can I make my new org2blog entries have no date property?

**Comment by priyadarshan** [comment]
Unless I am mistaken (please @grettke correct me if I am), one just needs to use `org2blog/wp-post-buffer`, instead of `org2blog-wp-post-buffer-and-publish`.

See snapshot of available commands:

![org2blog-post-commands](https://user-images.githubusercontent.com/1652143/31550038-48321eb6-b030-11e7-8b66-e741894af321.png)

**Comment by neonnoodle** [comment]
When `wp-post-buffer` is invoked, it creates a draft with the publication date as the date/time the command was invoked. I would prefer to avoid this, since if I then publish the draft in a week, it will be backdated instead of published the day-of.

**Comment by priyadarshan** [comment]
I also use that workflow. When one push a draft to WP, `org2blog` will write the date in the corresponding Emacs buffer.

When I need to publish the draft, I just change the date to whatever date I need, or, if I want the date at publish time, I just delete the `:POST_DATE:` property and `org2blog` will smartly assign the current date.

**Comment by neonnoodle** [comment]
I see. OK. I would prefer to be able to leave the date essentially "blank," but I will simply change the date at publication time if this is not possible otherwise. Thank you!

**Comment by priyadarshan** [comment]
I think one could write a small elisp code to remove `:POST_DATE:` and add it as a post hook to org2blog. I am not sure how to do that, though.

**Comment by grettke** [comment]
@priyadarshan You got it right.

@neonnoodle I think I understand what you are saying. There is a friction between the idea of how Org2Blog should and does work here.

One perspective says that it should work like any other Org-Mode exporter: set the properties, here the `POST_DATE` (before, now, later, or empty so create it at that moment), export to WordPress, it aka publish it, and you are done. This is now it does work and it makes sense if you are OK with the Org-Mode publishing abstraction.

Another perspective says that it should work more like the WP GUI. It ought to follow the flow of 
the GUI and work like that. If it doesn't have `POST_DATE` then only add it upon posting. This is friendlier. It is more familiar if you are coming from WP. 

Both approaches make sense and I like both of them And I'm not sure yet how they can be integrated. It doesn't feel right to lock Org2Blog down to either one approach or the other: because if it makes it harder to use it then it doesn't make sense to make the change. On the other hand, conflating the two models (Org-Mode exporting versus the WP model for publishing using the GUI) makes it confusing if you already know Org-Mode.

Maybe it is simple as adding a new function `publish-immediately`. It would reset the the `POST_DATE` like you @neonnoodle explained. That way you don't have to much around with deleting `POST_DATE` but at the same time it uses the WP GUI phrasing. 

You @priyadarshan  wouldn't have to deal with a hook here either: and publish time it would just delete the `POST_DATE` and let the existing function re-create it like normal. It should be pretty simple.

**Comment by neonnoodle** [comment]
Thanks for your response. 

In reality, much of this issue stems from Wordpress' UI deficiencies. There is still no easy way to clear the publication date of a post, short of deleting the field in the MySQL database. In my search for answers to this question, I have found multiple people asking WP support how to reset or clear the date, and in each case they are told to manually set the date at the time of publication. Clearly I am not the only one who wants this to work! 

Org2Blog is fabulous otherwise, and if a flag were added for manipulating the posted date, that would be terrific.

**Comment by grettke** [comment]
> if a flag were added for manipulating the posted date, that would be terrific.

@neonnoodle Please elaborate on where that flag would live, what are its values, and how the system would behave differently because of it. This is a non-technical question. What I want to know most is from your perspective what would make it an enjoyable experience to use this feature and functionality.

**Comment by neonnoodle** [comment]
Speaking only to my own use case, I'd find it sufficient to have a keyword in the wp-blog-alist like `:set-draft-published-date` with either `t` or `nil`. I suppose this could be overridden on a post-by-post basis with something in the `#+OPTIONS:`, but I never need the date to be set prior to the true "Publish" action.

**Comment by grettke** [comment]
I hear you. 

I will close this ticket once I create a new ticket for this topic.

**Comment by grettke** [comment]
Since the workaround is as easy as deleting the post date before you publish I'm going to close this issue.
