### ISSUE TITLE
Feature Request: REST API

### ISSUE THREAD

**Issue by neonnoodle** [org2blog/org2blog#253]
I am aware that this would likely constitute a complete rewrite of org2blog. However, the REST API seems to be "the future" of WP integrations.

**Comment by grettke** [comment]
I hear you.

[MetaWeblog](https://github.com/org2blog/metaweblog) does all of the heavy lifting. So once we replaced that with the REST API (probably write a package for it) not much would change here.

@titaniumbones Also [posted](https://github.com/org2blog/org2blog/issues/203) about it. And maybe _the right time_ is coming soon. Just a gut feeling because I haven't learned Org2Blog completely and this would be the right time to do it.

**Comment by titaniumbones** [comment]
I'm interested in this as well, but I'm not actively using org2blog right now (switched to hugo for most things) and more importantly, I don't really know anything about the REST API. Maybe the thing to do would be to start a new `rest-api` branch in this repo and try to at least sketch out the scope of the work in a set of smaller issues.  Then we could slowly add features & maybe assign some of the work to each of us.

It looks like authentication is a bit of an issue as [different methods have been hived off as plugins](https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/#authentication-plugins) instead of built into the main code base.  So, I guess that would be a place to start.

**Comment by grettke** [comment]
And proof-of-concept branch makes sense.

I figured that I could look at how they did it in a Python or Ruby binding to get a sense of the easiest way to do things.

**Comment by grettke** [comment]
Is something like [this](http://blog.jenkster.com/2013/10/an-oauth2-in-emacs-example.html) what you are looking for?

**Comment by titaniumbones** [comment]
yeah maybe :grin: but that's for oauth2; WP uses oauth1, and I'm not sure there's current emacs support for that?

**Comment by grettke** [comment]
I will keep digging.

**Comment by grettke** [comment]
I took a look. I don't have the guts to do this at this time. In the future definitely because future proofing and easier maintenance are why.

**Comment by grettke** [comment]
I added a feature request for WordPress REST APIs in the readme.
