### ISSUE TITLE
error in process sentinel: Multibyte text in HTTP request

### ISSUE THREAD

**Issue by rogorido** [org2blog/org2blog#266]
Thank you for filing this bug report. To make it easier for you and easier for
us please answer these five short questions:

- What version of Org2Blog are you using (`org2blog/wp-version`)? 1.0.3
- Did you review the wiki or the issues to see if this bug is already explained or reported? yes 
- What did you do? I tried to post a post with UTF8 characters (ñ, etc.)
- What did you see instead? error in process sentinel: Multibyte text in HTTP request: POST /xmlrpc.php HTTP/1.1

This is an old error which should already be solved, but I'm getting this error message with emacs 26.1. Any idea?

**Comment by grettke** [comment]
Hi @rogorido Sorry to hear that, we'll get it resolved soon. 
My gut reaction is that there is an old copy of xml-rpc somewhere in your load path. For example in your ELPA (or other cache). The reason is that I (and others) have faced this before. The reason for the issue was that Emacs 26 made a correction resulting in the error (correctly) showing up. xml-rpc was updated [here](https://github.com/hexmode/xml-rpc-el/commit/8f624f8b964e9145acb504e4457c9510e87dd93c). The xml-rpc version number did not increase, so if you installed it via ELPA then you need to delete it and reinstall it. Please try that out. If that doesn't resolve it then I have some next steps for tracking things down.

**Comment by rogorido** [comment]
@grettke thanks a lot. It works now. Is there a reason why xml-prc did not increase the version number?

**Comment by grettke** [comment]
@rogorido Good question. I don't know. You know, you can't be the only one needing to do this so I will notify people on Reddit and also the mailing list. Thanks for reporting this.

**Comment by rogorido** [comment]
@grettke thanks!
