### ISSUE TITLE
How to avoid automatic inserted \<p\> tags?

### ISSUE THREAD

**Issue by realasking** [org2blog/org2blog#269]
Hello!
I noticed that each posts published with org2blog have been inserted \<p\> and \</p\> markup tags between paragraphs. How to avoid them ? I'm accustomed to use markdown to write blogs with a plugin on wordpress site, the additional tags broke such function. If I could avoid such tags ? I'm freshman on org2blog, and expect your answer. Thank you.

**Comment by grettke** [comment]
Org2Blog lets you write in Org mode and publish to WordPress so it doesn't care what markup language it uses to do so. Right now it uses HTML because that has first class support in WordPress. It goes from Org mode to HTML to Org2Blog to WordPress.

Do you mean that you configured your blog to use Markdown, and that Org2Blog is generating HTML instead of Markdown and that is making those "broke tags"? The previous explanation is why. Do youo want it to be Markdown -> WordPress?

**Comment by realasking** [comment]
> Org2Blog lets you write in Org mode and publish to WordPress so it doesn't care what markup language it uses to do so. Right now it uses HTML because that has first class support in WordPress. It goes from Org mode to HTML to Org2Blog to WordPress.
> 
> Do you mean that you configured your blog to use Markdown, and that Org2Blog is generating HTML instead of Markdown and that is making those "broke tags"? The previous explanation is why. Do youo want it to be Markdown -> WordPress?

Thanks for your reply. Yes,  I want it to be Markdown->WordPress through org2blog. I have installed some markdown plugins such as `WP Githuber MD` on my blog, which will translate markdown to the web. When I used org2blog, I have found posts were all grouped with \<p\> tags after posts been published, like:
\<p\> ## Title2 \</p\>
\<p\>```bash\</p\>
Which makes MD tags lost their functions. Is there any method to make org2blog generating HTML without such tags?

**Comment by grettke** [comment]
I think you want this

    #+BEGIN_EXPORT html
    ## Title2
    ```bash
    #+END_EXPORT

**Comment by realasking** [comment]
> I think you want this
> 
> ```
> #+BEGIN_EXPORT html
> ## Title2
> ```bash
> #+END_EXPORT
> ```

Thank you very much! It's what I want.
