### ISSUE TITLE
Some confusion surrounding metaweblog

### ISSUE THREAD

**Issue by tarsius** [org2blog/org2blog#281]
After having removed it in 2011 with #52, have recently reintroduced `metaweblog.el` into the `org2blog` package. Currently things are broken as a result. We now have two packages providing the `metaweblog` feature and they don't provide the same version of the library. If you need some guidance, I would be happy to help.

**Comment by grettke** [comment]
Thank you for reaching out! 

Yes I do need some help here regarding how to proceed.

When we moved `metaweblog` to it's own repo we did it with the best of intentions: software engineering best practices and reuse and all of that. It was a great idea. In practice [8 years later](https://github.com/org2blog/metaweblog/issues/8) though no other packages were using it. Only `org2blog` uses it. So the plan was to reintegrate into the `org2blog` at some point. 

When I did the recent work on `org2blog` it seemed like a good time to move `metaweblog` back into the repository. I read about how to update the recipe to [point at a file in this repo](https://github.com/melpa/melpa#example-multiple-packages-in-one-repository). My plan was that once I finished working on `org2blog` I would update the `metaweblog` recipe using the multiple-packages-in-one-repository strategy (avoiding having two copies of `metaweblog` out there) then archive the Github repository. 

This was my plan in a todo list, then I forgot to review the plan. So I never did this. That is mistake #1.

When I imported `metaweblog` I didn't change the functionality. The only thing I did was add package metadata, revise some function documentation, and prepend the correct namespace to everything (along with defining aliases from the old names). I figured it would make sense to make the version the same as `org2blog`, v1.1.0. That didn't make sense though because there was no functional change. There are two versions that are identical. That is mistake #2. 

I am thinking that the first thing that needs to happen is regarding #2: `metaweblog` needs to have its version number returned to "1.0.1" from "1.1.1".  Because it is true. Once that is done I need to address #1.

I am thinking that regarding #1 I need to convert the recipe to the multiple-packages-in-one-repository strategy. 

Combined this will keep the package number correct, and transparently transition to the new repo location. 

What do you think?

**Comment by tarsius** [comment]
*The plan* sounds like a good plan. I recommend you do that right away, fixing mistake A.

Not sure if I even consider mistake B to be a mistake. I recommend you leave the version as it is (1.1.1). After all you *did* change something; you added the standard boilerplate and stuff.

So (1) adjust the recipes (2) archive the old separate repository. That should do it.

Mention me in the pr for the recipe changes and I'll merge it quickly.

**Comment by grettke** [comment]
Gotcha. [Done](https://github.com/melpa/melpa/pull/6495).

**Comment by tarsius** [comment]
> archive the old separate repository

... and add a link to the README.org, pointing to the new location.

**Comment by grettke** [comment]
The recipes are updated
