### ISSUE TITLE
Newly published posts are blank besides title

### ISSUE THREAD

**Issue by andyptt21** [org2blog/org2blog#282]
Recently updated to 1.1.1 and now I'm unable to publish new posts. When I login to my account I get the following warning:

Error (org2blog/wp): I’m sorry I ran into a problem trying to load tags inside of ‘org2blog-user-login’.
Error (org2blog/wp): 2019-11-17T17:06:50-05:00
Please report that along with the following details:
(void-function metaweblog-wp-get-tags)
Org2Blog Runtime: Org2Blog 1.1.1, Emacs 26.3, Org Mode 9.2, MetaWeblog 1.0.1, XML-RPC 1.6.12

When I try to publish a buffer I get another prompt to login, and then the following warning:

Error (org2blog/wp): I’m sorry I ran into a problem inside of ‘org2blog--upload-files-replace-urls’.
Error (org2blog/wp): 2019-11-17T16:59:40-05:00
Please report that along with the following details:
(void-function metaweblog-get-file-properties)
Org2Blog Runtime: Org2Blog 1.1.1, Emacs 26.3, Org Mode 9.2, MetaWeblog 1.0.1, XML-RPC 1.6.12

A new post is made to my blog but everything besides the title is missing.

**Comment by grettke** [comment]
Hi @andyptt21 It sounds like Org2Blog is trying to use a functions with the new package prefix and it can't find them. What jumps out here is that Org2Blog is at version 1.1.1 and MetaWeblog is at version 1.0.1. MetaWeblog should be at version 1.1.1: that is when the function new function name was added. 

In Org2Blog v1.1.1 MetaWeblog got imported into the Org2Blog repo. Technically it shouldn't matter, but, I wonder if there are two copies of MetaWeblog in your load-path and v1.0.1 is getting loaded first. Another simpler thing might be that metaweblog v1.0.1 is installed instead of the newer v1.1.1. A quick way to address this if you are using a package manager would be to try the following:

Find your `elpa` directory. It is usually something like `~/.emacs.d/elpa`.

Does it have both a metaweblog and org2blog folder in there? What are the version numbers? They should be the same. I'm guessing that metaweblog is at the old version. If this is the case then deleting reinstalling metaweblog should result in Org2Blog using the correct metaweblog version 1.1.1.

If you aren't using a package manager then please paste the value of `load-path` in here. Is v1.0.1 getting loaded before v1.1.1 somewhere in the path?

**Comment by andyptt21** [comment]
It works again, thank you! You were correct - the solution was going into ~/.emacs.d/elpa/, verifying that the versions of the two packages were different, deleting the directories, and reinstalling. Thanks for your prompt reply and a great package!

**Comment by grettke** [comment]
So glad to hear! You are welcome.

Happy blogging!
