### ISSUE TITLE
Image upload problem

### ISSUE THREAD

**Issue by higham** [org2blog/org2blog#289]
Uploading of images is no longer working for me using org2blog 20200303.418 and Org 9.3.6
(both the latest on Melpa at the time of writing).  It last worked for me about a month ago, but I have not tried since.  For example, 

file:./images/berr-fig.jpg

is translating into

<div class="figure">

<img src="./images/berr-fig.jpg" alt="berr-fig.jpg">

</div>

on Wordpress.  Org export of the same Org file to html and to
LaTeX does correctly render the image.

**Comment by grettke** [comment]
Gotcha. I will look at this ASAP.

**Comment by grettke** [comment]
@higham I disabled that feature by default in the last release because its behavior was confusing most users. Therefore breaking it for you: sorry for the trouble. As far as I could tell very few people use this feature so I made the change.

Add this to your configuration and try posting again

    (setq org2blog/wp-image-upload t)

Let me know how it goes.

**Comment by higham** [comment]
That works - many thanks, Grant!  It's an extremely useful feature.
