### ISSUE TITLE
sourcecode is exported differently?

### ISSUE THREAD

**Issue by cryoguy** [org2blog/org2blog#291]
When `org2blog/wp-use-sourcecode-shortcode` is set to  `nil`, the sourcecode is exported with `<pre> </pre>` tags, but code was decorated with html (from rainbow-identifier package), as shown [here](http://tech.memoryimprintstudio.com/covid-19-data-visualization-with-r/).  I am using crayon highlight, so I need it to export with `<pre> </pre>`tags.  

I end up doing the following way:  set  `org2blog/wp-use-sourcecode-shortcode` to  `t` change the tag manually to `<pre></pre>` after exporting. 

Is there any way to force org2blog to export just plain code?  I am using Emacs 26.3 and org-mode 9.3.6

**Comment by cryoguy** [comment]
I solved it by adding the following to my init file.
`(setq org-html-htmlize-output-type nil)`

**Comment by grettke** [comment]
@cryoguy Thanks for sharing that. As you see, behind the scenes Org2Blog uses the Org HTML exporter. Usually this never causes an issue, however in this case working with Crayon Highlight it did. I would like to update the documentation so that people know how to handle this in the future. However I can't say that I completely understand the problem well enough. That said, I think you do because you both ran into it and resolved it. If you are willing then can you submit a patch to `README.org` or even explain more in this comment about the problem, why that resolved it, and how you think the documentation should change (if anything) so that people can? I understand that you did resolve it and that the resolution is here for people to utilize in the future and I thank you for that. If you have the time and you think it is useful then I would love to here how Org2Blog could better address this in the future. Happy blogging!

**Comment by cryoguy** [comment]
Sorry about the delay!  The org mode code highlight is best explained [https://github.com/gongzhitaao/orgcss](here).  I would love to submit a patch if you would educate me on how to do that.   Thank you very much for the wonderful work.  I have been using org2blog for years for my [tech.memoryimprintstudio.com/](blog).

**Comment by grettke** [comment]
@cryoguy Thank you for getting back to me, your patience with me getting back to you, you kind words, and explaining how to move this forward. Here is what I think:

From how I understand it you can get the behavior that you want if you:

1.  Include the CSS of that project 
2. Disable Org2Blog shortcodes if they are turned on

In your Org Mode file add this

```
#+BEGIN_EXPORT html
<link rel="stylesheet" type="text/css" href="https://gongzhitaao.org/orgcss/org.css"/>
#+END_EXPORT
```

In your Org Mode configuration make sure that this is set

```
(setq org2blog/wp-use-sourcecode-shortcode nil)
(setq org-html-htmlize-output-type 'inline-css)
```

Here is the test.

In this screenshot **"A"** `org-html-htmlize-output-type` is set to nil:

<img width="541" alt="Screen Shot 2020-08-13 at 12 53 02 PM" src="https://user-images.githubusercontent.com/2521647/90169622-75bcd880-dd64-11ea-81ab-0af63a7f443d.png">

In this screenshot **"B"** `org-html-htmlize-output-type` is set to `'inline-css`:

<img width="526" alt="Screen Shot 2020-08-13 at 12 54 07 PM" src="https://user-images.githubusercontent.com/2521647/90169642-7e151380-dd64-11ea-9fcf-6724928c7502.png">

What do you think?
