### ISSUE TITLE
Support for #+begin_abstract in some form?

### ISSUE THREAD

**Issue by lockywolf** [org2blog/org2blog#305]
- What did you do?

I wrote an abstract for my post in the `#+begin_abstract #+end_abstract`  blocks.

- What did you expect to happen

Be it either exported with a "cut" (`#+html: <p><!--more--></p>`) tag after `#+end_abstract`, or be exported as a wordpress excerpt.

- What happened instead?

The "abstract" is exported as ordinary text.

- Did you review issue tracker to see if this bug is already
  reported or resolved?

yep

- Did you review the README about how this feature works?

Yeah :)

I think that a simple and 90% valid idea would be to just insert the wordpress' "cut" pseudo-tag.

**Comment by grettke** [comment]
@lockywolf Since Excerpts are new to me, I did some research and
[this](https://wordpress.com/support/excerpts/) is what I found:

> Excerpts are optional hand-crafted summaries of your content.
>
> Excerpts are ideal for creating one to two sentence descriptions of
> the content on a page or post. These Excerpts can be used by different
> themes as a preview, in place of showing the full post or page
> content.
>
> Examples of places where Excerpts may show, depending on your Theme:
>
> -   Search results
> -   Blog Page
> -   Portfolio Page
> -   Featured Content on the Homepage

When I read further, I see that Excerpts are woven into the core
features of WordPress. In particular, you can configure it with the
Editor, style it, use it for RSS feeds, and Themes do things with it.
What about the More-Tag tag, though? For that, I read
[here](https://kinsta.com/knowledgebase/wordpress-excerpt/#how-to-use-the-more-tag-in-place-of-excerpts)
(in addition to a bunch of their pages on the same topic).

Most articles only talk about Excerpts versus More in technical terms,
but their difference becomes apparent after you read enough. Excerpts
contain the most description, and More-Tag has the least. Therefore the
easiest way to explain the More-Tag is in comparison to the other.

Excerpts are brief post content descriptions to be used automatically
(aka programmatically) throughout the rest of the site in different
features (lists, summaries, RSS feeds) probably exposed via Theme.
More-Tag is none of that.

The More-Tag splits your post into two parts: the content before the
Teaser, the optional message for the Teaser, and then content displayed
only after clicking the \"Next\" link. The idea is to show some content
to the user to get them interested, and when they are, they will click
next. Maybe it is two sentences, two paragraphs, or two pages: there are
no restrictions here. Whatever size you wish will work fine. There is no
1-2 sentence recommended restriction.

The More-Tag is not a \"thing\" though in the WordPress universe. It
isn\'t a Post, or a Page, or an Excerpt. It is just a tag that modifies
your post (splitting it up as explained above). Despite some overlap in
their use, the best way to describe a More-Tag is that it is a content
Teaser, not an Excerpt, and in fact, nothing: it modifies a page, and
that is all. You can only have one Excerpt per page, and you can use the
More-Tag as many times as you want (I didn\'t research the behavior
though). If you are still awake and reading this, kudos to you: here is
where I think this topic is going.

An Abstract is [on
average](https://www.crowdwriter.com/blog/how-long-should-an-abstract-be)
100-500 words. It is a paragraph or two or three. That is a lot more
than 1-2 sentences, the preferred length of an Excerpt. To your point, I
agree: an Abstract translates to a More-Tag. That leaves the question of
how to move forward.

First, try the helper function to insert the More-Tag. Run
`org2blog-user-interface`, choose `[Insert A]`, then `[More Tag]`.
Don\'t add a message and hit return. It will insert this:

``` {.example}
@@html:<!--more-->@@
```

You will see a split like this (on my blog):

<img width="543" alt="Screen Shot 2020-09-08 at 6 23 27 PM" src="https://user-images.githubusercontent.com/2521647/92541022-86992680-f20a-11ea-87d3-f2396744fc3e.png">

Then do the same thing again and specify a message:

``` {.example}
@@html:<!--more Click here to read more-->@@
```

Save it to your blog, and you will see a split like this:

<img width="573" alt="Screen Shot 2020-09-08 at 6 25 03 PM" src="https://user-images.githubusercontent.com/2521647/92541039-94e74280-f20a-11ea-8ed5-aa9aa398a032.png">

The More-Tag lets you use a description or not.

From a superficial glance, I don\'t see a way to associate the
description with the `abstract` block, which I would have to research.

Otherwise, it seems like there isn\'t any more to using the More-Tag.
The Abstract would get pasted into the content, then a More-Tag without
a comment, then the remaining content.

What do you think?

**Comment by lockywolf** [comment]
Maybe I was wrong, and this does not need any special treatment. I'll close this, and think more.
