### ISSUE TITLE
load-path not being set by autoloads

### ISSUE THREAD

**Issue by podiki** [org2blog/org2blog#310]
Org2Blog doesn't load with `use-package` after initial install (i.e. installs and works fine, until reopening emacs). The problem is that the `load-path` is not updated with Org2Blog on later loads. I believe the problem is in the autoloads. Every other package I looked at (which I think are all autogenerated on install rather than in the package repository) has the following at the top:

```
(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))

^L
```

So when installing everything works and the `load-path` has the Org2Blog directory in it. However, upon closing and restarting emacs, whether there is a `use-package` line in the config file or you do it separately, it doesn't work with the message `Error (use-package): Cannot load org2blog`.

Checking `load-path`, the Org2Blog directory is not in there, I believe due to that missing autoload. You can `(require 'org2blog-autoloads)` but that still doesn't help. I've added what I think is the missing line, but it doesn't work as I think the autoloads file doesn't get loaded at the right time. If I `load-file` the autoloads it works then. I've played with different `:ensure` and package names with `use-package` as well as an explicit `(require 'org2blog-autoloads)` in `:config` but no success yet.

Anyway, I haven't quite figured out all the autoloads business, so I'm not exactly sure what is wrong or how to fix it with `use-package`. I can try a fork and using `straight` to load it, but haven't tried yet in case there's something obvious missing. Still, the missing `load-path` declaration in the autoloads versus other packages makes sense that the `load-path` does not have Org2Blog.

I also can't completely confirm that this is not on my end without more testing. I don't think I had this problem long ago, but I'm not sure since that was a very long time ago (and probably before I used `use-package`).

**Comment by podiki** [comment]
This may be a `use-package` problem, as adding in `straight` fixes this. I believe because `straight` directly adds the package build directory it creates. I'm not sure what `use-package` does, but I think just relying on `package` and using autoloads? I'll have to investigate...

**Comment by podiki** [comment]
(Sorry for the spam.) I think I've finally found similar issues and discussions, but haven't yet followed it through completely yet. Looking at joaotavora/sly#244 has helpful info and links to other relevant issues. I think the key thing is newer emacs and `package-quickstart` (which I use, though not sure if correctly).

I'll investigate and let you know what I find.

**Comment by grettke** [comment]
@podiki Sounds good. Thanks for sharing. Report back.

Consider a couple things:

- Few of us have other Emacs people to speak with. Simply explaining something to another person often results in solving the issue at hand. Additionally talking it through also reaches a resolution. Therefore using support issues to do so is a great option. I certainly never hesitate.
- When we face an issue, we are rarely the first. It is better to capture the issue, the details, the thought processes, and everything to do with the process so that future users can benefit from that process. You often find this when issues facing your system have already been solved in your system.

Keep at it.

**Comment by podiki** [comment]
Agreed on both points. The fix is easy, and the reasoning not too bad once I figured out what was going on. This is from an emacs change in 27, a year or two ago now (which made it less obvious for me to find).

Anyway, let's start with the punchline of what Org2Blog needs to resolve this issue. A few choices:

1. Remove `org2blog-autoloads.el` from the package (or Melpa recipe I suppose), allowing it to be fully generated on package install.
2. Update `org2blog-autoloads.el` with the file generated by `(package-generate-autoloads "org2blog" "/path/to/org2blog/")`. I don't think this is critical when doing most updates to Org2Blog, but needed for that `load-path` line (see below for why).
3. Add the `load-path` line noted above, to `org2blog-autoloads.el`.

The easiest may be 1, to remove the autoloads file so it can be generated on package install and not have to worry about it here at all. The only downside I saw was if someone wants to do something like just use this repository directly and wants the autoloads without doing the step of generating them. Otherwise can do 2 or 3, which I think will be basically the same at the end of the day.

Now we come to the why. There's some key points I learned from some trial and error and reading online, which made this a little tricky to diagnose as one that hasn't dealt so much with packaging. I'll summarize the main points for (at least) my own education and memory:

- The autoloads file is always (?) generated on install, but if the file exists the top commentary lines and `load-path` are not added. See the function `package-autoload-ensure-default-file` which is called by `package-generate-autoloads`. Presumably this is to not clobber an existing file or some other good reason (?). This made it tricky as I didn't understand at first when the `load-path` line was being generated or not when I was debugging.
- In other words, after installing Org2Blog the autoloads file is the one generated by emacs, not the provided one (unless using something like `straight`, where the repo is used directly?)
- `package-quickstart`, from my basic understanding, is a file that concatenates all the autoloads for easy loading at startup. This is generated by `package-quickstart-refresh` on things like package install. So if you change autoloads otherwise, quickstart is not updated and thus the changes not made on emacs load (this caught me), without calling refresh directly.
- (I'm not sure about this issue without using quickstart.)
- So for a general user that just does `package-install` or `use-package`, the autoloads file does not have the `load-path` and thus won't work upon restarting emacs. Regenerating the file (without deleting first) won't add the `load-path`, and will need to update `quickstart` if the line is added.

A bit tricky, but in the end rather documented, other than the `load-path` line not being generated if the autoloads file exists. It looks like at least `sly` and `slime` dealt with this based on the linked issue, and I think I summarized the possible changes for Org2Blog. Unless there's a good reason for keeping the autoloads file, probably just easiest to go with 1 and remove it.

**Comment by grettke** [comment]
@podiki Thank you very much for that.

It seems like there is an issue with it running on Emacs 27. 

Since this task is the 2nd in the queue right now, I will let you know when I think I will get started on it.

Thanks again.

**Comment by podiki** [comment]
Any update on this? Trying to use org2blog with this bug means wiping and reinstalling the package each time, and I think just removing the autoloads is all that is needed.

**Comment by mykolan** [comment]
It seems I have a similar issue. I'm not a very technical Emacs user, but the overall description fits well:
1. I use Emacs 27.2 (mainly on Windows)
2. I've tried to install `org2blog` via `use-package` (it's my preferred method), via `quelpa` and from a .tar file. Any first install works well.
3. However, every next time I run Emacs, I have a message 'Error (use-package): Cannot load org2blog'
4. So if I want to post anything at a given day, my workaround is reinstall the package.

**Comment by podiki** [comment]
Thanks for confirming @mykolan, right now I do the same thing.

@grettke any updates on this? Simply removing the file should be the right (and easy) thing to do.

**Comment by grettke** [comment]
@podiki Sorry. Sorry. Sorry. Thank you. Thank you. Thank you.

Your investigation and references explain it perfectly.

I'm going to work on this now.

**Comment by grettke** [comment]
@podiki Attached is package with the fix. First decompress it: github disallows tar files. You can install it with `package-install-file`. If you have a chance then please let me know how it goes.
[org2blog-20220819.149.tar.zip](https://github.com/org2blog/org2blog/files/9378683/org2blog-20220819.149.tar.zip)

It removes the autoloads file from the repo.

I tested it on Emacs 27.

[This](https://github.com/org2blog/org2blog/tree/noautoloads) is the branch.

**Comment by grettke** [comment]
@podiki Attached is package with the fix. First decompress it: github disallows tar files. You can install it with `package-install-file`. If you have a chance then please let me know how it goes.

[org2blog-20220819.200-1.tar.zip](https://github.com/org2blog/org2blog/files/9378714/org2blog-20220819.200-1.tar.zip)

It removes the autoloads file from the repo.

I tested it on Emacs 27.

[This](https://github.com/org2blog/org2blog/tree/noautoloads) is the branch.

**Comment by podiki** [comment]
@grettke I did a quick test: installed the version you linked and `org2blog-user-interface` works on install. Restart emacs and this works again, when it didn't before. This is with emacs v28.1.

**Comment by grettke** [comment]
> @grettke I did a quick test: installed the version you linked and `org2blog-user-interface` works on install. Restart emacs and this works again, when it didn't before. This is with emacs v28.1.

Thank you for testing so quickly.

I will commit the fix (it will close this ticket) and it will get included in the next MELPA build which are quite frequent. After that you should get the update once you update your packages and things should continue to work correctly for you. Once I commit it I will also close this task: it should work fine. If you want please let me know the upgrade goes right for you from MELPA. 

You investment in time and effort along with your generous patience are greatly appreciated. Life can be profoundly unpredictable and it is people like you that help make it easy to know that a better future is not only possible but in fact likely.

**Comment by podiki** [comment]
Happy to help and see it working smoothly again!

By the way, perhaps might be good to have a new tag/release? Not sure how that works for most people, but could be useful for some package managers or people following tags/releases only. But that is a separate matter perhaps.

**Comment by grettke** [comment]
> Happy to help and see it working smoothly again!

You made it happen: thank you again.

> By the way, perhaps might be good to have a new tag/release? 

Yes absolutely.

> Not sure how that works for most people, but could be useful for some package managers or people following tags/releases only. 

Most `use-package` users run against MELPA (unstable) because you get the new features and bug fixes faster. You also get the bugs faster. However bugs are relatively rare. So they are getting every single change every hour or so.

A good amount of people also run against MELPA Stable. MELPA Stable *only* includes tagged releases. Org2Blog addresses both approaches. Other package managers like Straight are designed to follow any approach, these being one too. Even managing by hand obviously work well (that is how we work against the code directly).
 
> But that is a separate matter perhaps.

It is all related. Org2Blog has a real plan about managing new tags and releases. Specifically you can read about [The Official Release Process here](https://github.com/org2blog/org2blog/blob/master/docs/ReleaseProcess.org). 

That is the only way many of us could remember it. This process is not humongous but it catches probably 80% of the easy stuff and out of the remaining 20% it catches 10% of the stuff that should never get out. There are still ways to make it better of course.

If you are curious about stuff like releasing a package you should read through it if you have a chance. Everything is written down because it is all important yet not everyone can remember that many steps (for example I can't). When you finish up features, you typically use up all your mental energy and enthusiasm to finish it. Then when you get to the release process you are out of steam "I just want to deploy it and be over with it!" In the interest of users time though it is worth going through the process. Many times you can probably get away with skipping it (I have for example) but you have to be really sure about it.

In the case of this fix I will wait a few days or a week just to make sure things worked out fine—and then tag it.

Since I was a little unsure about /myself/ breaking one of the autoloads I pre-emptively created a support ticket [here](https://github.com/org2blog/org2blog/issues/323) and reported it in /r/orgmode and /r/emacs so that if anybody came to report it they would immediately know how to resolve it. As you explained precisely the whole thing was new to you and also me, and the topic was somewhat murky, so you know: so be it. We do our best and move forward.

**Comment by podiki** [comment]
Great, thanks again @grettke
