### ISSUE TITLE
Error during request: 500

### ISSUE THREAD

**Issue by toddfoster** [org2blog/org2blog#317]
Posting or updating a post returns:

```
Error (org2blog/wp): I’m sorry I ran into a problem on post: “Notices for 5 August 2021” (ID “4685”) inside of ‘org2blog-entry-save’.
Error (org2blog/wp): 2021-08-10T09:25:39-04:00
Please report that along with the following details:
(error Error during request: 500)
Org2Blog Runtime: Org2Blog 1.1.10, Emacs 26.3, Org Mode 9.4.4, MetaWeblog 1.1.1, XML-RPC 1.6.15
```

My configuration worked fine. Then... I changed hosts. I moved to dreamhost, and the transfer seemed flawless: everything looks exactly as it did. The WP version, and very possibly the version of php or other tools, may be more up-to-date now.

The xmlrpc.php is still active -- though possibly updated in the move. My old site had complained about the xmlrpc getting hit a lot, so I changed its name to add a little security-through-obscurity. But the result is likely that updates to my wpcore probably never updated the xmlrpc I was using -- successfully! The first thing I tried was moving back to using the default xmlrpc.php and restarting emacs.

Now the subtree in org will be given an _id_ and _postid_ but doesn't actually get pushed up. My example case is just some text with links and minor formatting in markdown.

Suggestions where I should look next?

Thanks.

**Comment by tftorrey** [comment]
For @toddfoster or anyone finding this by search in the future, as I did, org2blog fails to post multi-paragraph content to WordPress on DreamHost because of a ModSecurity pattern DreamHost uses that matches newlines. This can not be fixed or overridden in .htaccess (Org2Blog might be able to craft non-offending newlines, but I kind of doubt it), but the DreamHost support was very helpful to add in exceptions in their configuration to make it work. They were able to look at the error log, find the offending rule, and make the exception in just a few minutes.

**Comment by toddfoster** [comment]
tftorrey -- what a find! It makes sense the new host was the problem. Thank you for running this down, and even more for sharing what you found.
