### ISSUE TITLE
FR: Setting an featured image for a post

### ISSUE THREAD

**Issue by maroony** [org2blog/org2blog#58]
It would be nice to have an option for setting an featured image for a post, so that the added image is ONLY an featured image - that means, it should NOT appear in the post itself.

Btw: Great Work! ;-)

**Comment by drym3r** [comment]
Hi
Is this yet supported? If not, would you think about supporting it? It would be very nice
Thanks

**Comment by pymander** [comment]
Hello! The featured image piece is the only think keeping me from finishing the entire publishing process from within org2blog. Any chance of this being supported?

**Comment by grettke** [comment]
Hi @pymander . Thanks for reaching out.

Based on this thread, it is safe to say definitely "Probably yes." 

Since we've got a brand new feature request process, this feature request needs a new ticket.

Your perspective and participation on this feature are critical: I've never used Featured Image before, don't know its value, or why anyone would care about it, or how they may even want to utilize it from within Org2Blog. However: you do, which is excellent news because it changed this feature request from "impossible" to "possible"!

Can you help by creating a new feature request and link to it from here?

**Comment by pymander** [comment]
Hi @grettke! Thanks for the reply. I have created a FR as #315! I would be happy to help out by testing/debugging and contributing documentation.
